# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58ef787df60cbdb4113957b777755a502e69247402fcd2dc3b9173c57843d4820c00bac5c4fe649d499a7f37fc9554f3a5c06b45001dfcf5d3e0b7f0eb21590d

test:
  secret_key_base: 80247523b4e21bfad9128a90012c13a748dde02833529172c40bc9404003b755dd507402519f9c665a83490000500e29b69572ff7579de2a61f6fb6b887a34ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
